[build]
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "netlify/functions"

# Schedule the function to run every 1 hours
[functions."scheduled-blog-generator"]
  schedule = "0 */1 * * *"

# Configure function timeouts
[functions."*"]
  timeout = 30

